# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          - mvn --version
          - mvn clean install